export default {
  wide: '16:9',
  fit: 'cover',
  sizeOrigin: false,
  mainText: '明日方舟',
  subText: '-    ARKNIGHTS    -',
  mainFontSize: 140,
  subFontSize: 22,
  mainTextOffset: 0,
  mainTextSpacing: 128,
  letterOffsetY: [-5, 40, 26, 82],
  verticalTilt: 0.27,
  textShadow: true,
  textInvert: false,
  transparentBg: false,
  clipOffset: [32, 29, 57, 48],
  mimeType: 'png',
  quality: 0.6,
}
